### ISSUE TITLE
Python kernel path for jupyter

### ISSUE THREAD

**Issue by lnauta** [KaveIO/KaveToolbox#3]
When running ipython notebook I get the following error:
## import pandas

ImportError                               Traceback (most recent call last)
<ipython-input-1-d6ac987968b6> in <module>()
----> 1 import pandas

ImportError: No module named pandas

This is a known issue in jupyter:
https://github.com/jupyter/notebook/issues/397

and can be fixed by changing the path where jupyter loads the python kernel:
~/.local/share/jupyter/kernels/python2/kernel.json

This should be done automatically by KTB upon installation.

**Comment by rwlambert** [comment]
FAQ added in the readme. I have checked with a new standard ubuntu14 installation and I do not have this problem. FAQ added for the future release.
